name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install pytest pytest-cov
    - name: Run tests
      working-directory: ./server
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}  # Add this line
      run: |
        python -m pytest --cov=. tests/